import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import detailsStyles from "../styles/Details.module.css";
import { useState } from "react";
import { Steps, ConfigProvider } from "antd";
import PersonalDetails from "./components/PersonalDetails";
import Show from "./components/Show";
import Motivation from "./components/Motivation";
import Stepper from "./components/Stepper";
import {code, fire, user} from '../assets'
import Modal from "./components/Modal";
const Step = Steps.Step;


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const items = [
		{
			id: 1,
			title: "Personal Details",

		},
		{
			id: 2,
			title: "Step 2",
		},
		{
			id: 3,
			title: "Motivation",
		},
		{
			id: 4,
			title: "Step 3",
		},
		{
			id: 3,
			title: "Step 3",
		},
	];

	const [currentSlide, setCurrentSlide] = useState<number>(0);

	const [formData, handleFormData] = useState<object | undefined>({});

	const updateForm = (update: any) => {
		handleFormData({...formData, ...update})
		console.log(formData)
	}

	return (
		<>
			<Head>
				<title>FY Representative Forms</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Modal/>
				<div className={styles.container}>
					<div className={styles.leftcontainer}>
					<Stepper 
							current={currentSlide}
							Change={(n:number)=>setCurrentSlide(n)}
							items={[
								{
									title: "Personal Details",
									description:"Add your detail",
									icon:user
									
								},
								{
									title: "Show us what you got",
									description:"",
									icon:code
								},
								{
									title: "Motivation",
									description:"",
									icon:fire
								},
							]}
						/>
					</div>



					<div className={styles.rightcontainer}>
						{currentSlide === 0 && (
							<PersonalDetails currentSlide={currentSlide} setCurrentSlide={setCurrentSlide} updateForm={updateForm}/>
						)}

						{currentSlide === 1 && (
							<div className={detailsStyles.oneSection}>
							<div className={detailsStyles.sectionHeader}>
								<span>Step {currentSlide+1}/5</span>
								<h1>Showcase your Profiles</h1>
								<p>Show us What you got</p>
							</div>
							<div className={detailsStyles.sectionContent}>
								<div className={detailsStyles.oneField}>
									<label>GitHub Profile</label>
									<input type="text" />
								</div>
								<div className={detailsStyles.oneField}>
									<label>CP Platform Profile</label>
									<input type="text" />
								</div>
								<div className={detailsStyles.oneField}>
									<label>LinkedIn Profile</label>
									<input type="text" />
								</div>
								{/* <div className={detailsStyles.oneField}>
									<label>Describe yourself in one line</label>
									<input type="text" />
								</div> */}
								<div>
									<button type="button" onClick={() => {setCurrentSlide(currentSlide+1)}}>Next</button>
								</div>
							</div>
						</div>
						)}

						{currentSlide === 2 && (
							<div className={detailsStyles.oneSection}>
								<div className={detailsStyles.sectionHeader}>
									<span>Step {currentSlide+1}/5</span>
									<h1>Showcase your Profiles</h1>
									<p>Show us What you got</p>
								</div>
								<div className={detailsStyles.sectionContent}>
									<div className={detailsStyles.oneField}>
										<label>Describe yourself in 1 line</label>
										<input type="text" />
									</div>
									<div className={detailsStyles.oneField}>
										<label>What are you planning to make into CodeCell</label>
										<input type="text" />
									</div>
									<div>
										<button type="button">Submit</button>
									</div>
								</div>
							</div>
						)}

						{currentSlide === 3 && (
							<h1>HelloWorld 4</h1>
						)}

						{currentSlide === 4 && (
							<h1>HelloWorld 5</h1>
						)}
						
					</div>
				</div>
			</main>
		</>
	);
}
